version: "3"
services:
  php-server:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: php-custom-server
    volumes:
      - ./projetoPHP:/var/www/html
    ports:
      - "81:80"
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=banco-mysql
      - MYSQL_ROOT_PASSWORD=arthur123
    volumes:
      - ./docker/mysql_volume:/var/lib/mysql
